export { default as CommentService } from './comment.service'
export { default as AuthService } from './auth.service'
export { default as DiscountService } from './discount.service'
export { default as ProductService } from './product.service'
export { default as UserService } from './user.service'
export { default as WishlistService } from './wishList.service'
